#!/usr/bin/env bash
# Displays "Best School" but displays "Hi" on the 9th iteration

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 3 ]
  then
    echo "bad luck"
  fi
 if [ $index -eq 7 ]
 then
    echo "good luck"
 fi
  echo "Best School"
  ((index++))
done
