#!/usr/bin/env bash
# Displays "Best School" but displays "Hi" on the 9th iteration

index=0

while [ $index -lt 10 ]
do
  if [ $index -eq 3 ]
  then
    echo "bad luck"
  elif [ $index -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((index++))
done
